### ISSUE TITLE
tira o meu nome desse repo

### ISSUE THREAD

**Issue by ghost** [arufonsekun/faustop-language#34]
@arufonsekun @jeanchilger algum de vcs tira o meu nome desse repo. Tem nos arquivos:
- README.md
- /src/faustop/core/vars/DoubleType.java
- /src/faustop/core/main/util/Symbols.java

Não sei pq eu esperei tanto tempo pra pedir isso, mas, enfim.

**Comment by jeanchilger** [comment]
kjh jkhk, OK

**Comment by jeanchilger** [comment]
@arufonsekun pode deletar estar issue
